developer.addons.Item({
	id: 'ui.apps',
	group: 'ui',
	name: 'Apps',
	description: 'The app launcher rail. Every application registers one item here and becomes openable from the dock.',
	content: [
		'## What it does',
		'',
		'Apps are the top level of the shell. Every application registers exactly one item and the shell takes over: the launcher shows it, conditions across the whole UI react to it, and deep links open it.',
		'',
		'## Item essentials',
		'',
		'- `id` — stable slug like `developer` or `builder`',
		'- `name`, `icon`, `color` — how the launcher renders it',
		'- `links` — quick links shown on the launcher entry',
		'- `order` — position on the rail',
		'',
		'## Commands',
		'',
		'| Command | What it does |',
		'| --- | --- |',
		'| `ui:apps:open` | Opens an app by id, emits `ui.apps.open` |',
		'| `ui:apps:close` | Closes the active app, emits `ui.apps.close` |',
		'',
		'## Facade',
		'',
		'```js',
		'$ot.ui.apps.open(\'developer\');',
		'$ot.ui.apps.active(); // the active app item',
		'$ot.navigate({ app: \'developer\', mode: \'elements\' });',
		'```'
	].join('\n')
});
