developer.addons.Item({
	id: 'ui.screens',
	group: 'ui',
	name: 'Screens',
	description: 'Named navigate states with routes. A screen composes an app, a mode and route parameters, so any shell state is a shareable URL.',
	content: [
		'## What it does',
		'',
		'A screen is a named state of the shell bound to a URL. Opening a screen opens its app, switches its mode, resolves the route parameters through the `data` callback and writes the route into the address bar. Loading a matching URL does the same in reverse — every state is a deep link.',
		'',
		'The developer app is built from screens: `/developer/elements/:id/:tab` opens the elements mode with the element and the tab resolved from the URL.',
		'',
		'## Item essentials',
		'',
		'- `route` — one pattern or a list, like `[\'/developer/addons\', \'/developer/addons/:id\']`',
		'- `app`, `mode` — where the screen lives; a screen without an app closes the active one',
		'- `isDefault` — the screen a mode switch opens when the mode has more than one',
		'- `data` — called with the route parameters as `this`, returns live values every render receives',
		'',
		'## Data',
		'',
		'The `data` callback result is never persisted. It is recomputed from the URL on every load, so renders can receive whole items, not just ids.',
		'',
		'## Commands',
		'',
		'| Command | What it does |',
		'| --- | --- |',
		'| `ui:screens:open` | Opens a screen with parameters, emits `ui.screens.open` |',
		'| `ui:screens:close` | Closes the active screen, emits `ui.screens.close` |',
		'',
		'```js',
		'$ot.ui.screens.open(\'developer.element\', { id: \'cards-stat\', tab: \'code\' });',
		'$ot.ui.screens.active(); // the open screen item',
		'$ot.ui.screens.close();',
		'```'
	].join('\n')
});
